import { Button, Paper, TextField, Typography } from "@mui/material";
import { NextPage } from "next";
import { useState } from "react";
import { useSnackBar } from "../../hooks/useSnackBar";
import { isValidEmail, isValidPassword } from "../../utils/validator";
import ChatIcon from "../../public/chat.svg";
import Image from "next/image";
import Link from "next/link";
import Head from "next/head";

const LoginPage: NextPage = () => {
  const [email, setEmail] = useState<string>("");
  const [password, setPassword] = useState<string>("");
  const { snackbarInjector } = useSnackBar();

  const handleSubmit = (): void => {
    if (email === "" || password === "") {
      snackbarInjector("please provide email and password", "error");
    } else {
      if (isValidEmail(email) && isValidPassword(password)) {
        snackbarInjector("login success", "success");
      } else {
        snackbarInjector("incorrect email or password", "error");
      }
    }
  };

  return (
    <div className="page-container">
      <Head>
        <title>Chat App | Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="./chat.svg" />
      </Head>
      <Paper
        elevation={7}
        sx={{
          minWidth: 500,
          padding: 2,
          minHeight: 300,
          display: "flex",
          flexDirection: "column",
          justifyContent: "space-between",
        }}
      >
        <Image src={ChatIcon} alt="logo-icon" width={60} height={60} />

        <TextField
          type={"email"}
          label="Enter Email"
          value={email}
          onChange={(e) => setEmail(e.target.value)}
          size="small"
          color="primary"
        />
        <TextField
          type="password"
          label="Enter Password"
          value={password}
          onChange={(e) => setPassword(e.target.value)}
          size="small"
          color="primary"
        />
        <Typography color="primary" sx={{ textDecoration: "underline" }}>
          <Link href={"/signup"}>Don't have accont? signup here</Link>
        </Typography>
        <Button onClick={handleSubmit} color="primary" variant="contained">
          login
        </Button>
      </Paper>
    </div>
  );
};

export default LoginPage;
